name: atlantis
description: Flutter application for Atlantis app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.3
  flutter_bloc: ^6.0.6
  meta: ^1.1.8
  equatable: ^1.0.2

  cupertino_icons: ^0.1.3
  
  #sql_server_socket:
    #git:
    #  url: https://github.com/nippur72/SqlServerSocket.git
    #  ref: karyan40024
    #  path: patch-1

    
  # dart_mssql:
  #   git:
  #     url: https://github.com/MoacirSchmidt/dart_mssql.git
  #     ref: master




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/AtlantisIcono.png
    - images/containers.png
    - images/background.png
